services:
  db:
    image: mysql:8.0
    container_name: php_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: tiger
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - 1025:1025
      - 8025:8025

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    ports:
      - 8080:80

volumes:
  db_data:
